all_icons_show: 1
facebook_url: 'https://www.facebook.com/idewdot'
twitter_url: 'https://twitter.com/dewdots'
instagram_url: 'https://www.instagram.com/google'
linkedin_url: 'https://in.linkedin.com/company/google'
youtube_url: 'https://www.youtube.com/user/Google'
vk_url: ''
whatsapp_url: ''
github_url: ''
telegram_url: ''
vimeo_url: ''
slider_show: 1
slider_time: 5000
slider_dots: 'true'
slider_code: ''
front_sidebar: 0
google_font: local
comment_user_pic: 0
node_author_pic: 0
node_tags: 0
copyright_text: 1
scrolltotop_on: 1
css_extra: 0
css_code: ''
_core:
  default_config_hash: mLkSaJDZEv2S9kWh39agUO9tQnhgN5CmN1W2_zYT11o
